apiVersion: v1
kind: Service
metadata:
    name: mongodb-service
    labels:
        app: mongo
spec:
    ports:
        - name: mongo
          port: 27017
          targetPort: 27017
    type: LoadBalancer
    selector:
        app: mongo
