apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-cluster-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    hostPath:
        path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-cluster-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard
