apiVersion: v1
kind: Service
metadata:
    name: mongodb-service
spec:
    type: LoadBalancer
    selector:
        app: mongo
    ports:
        - port: 27017
          protocol: TCP
          targetPort: 27017
